const videoItem = [
	{
		img: 'https://cdn.igromania.ru/mnt/news/c/d/9/4/2/0/85047/18d4a3549f06a94a_1920xH.jpg',
		time: '14:20',
		ava: 'https://shutniks.com/wp-content/uploads/2020/04/volk_na_avu_6_05185110.jpg',
		videoName: 'CSS Grid Layout Tutorial',
		user: 'David Wilson',
		numberOfViews: '7 тыс',
		releaseTime: '3 часа назад',
	},
	{
		img: 'https://cybersport.metaratings.ru/storage/images/d2/0b/d20b0d35f3bc10e586a40b65885199e3.jpg',
		time: '19:55',
		ava: 'https://img3.akspic.ru/originals/0/3/7/9/4/149730-purpurnyjcvet-elektrik-verhnyayaodezhda-maska-purpur-1920x1080.jpg',
		videoName: 'Python Crash Course',
		user: 'Sophia Taylor',
		numberOfViews: '15 млн',
		releaseTime: '2 дня назад',
	},
	{
		img: 'https://i.pinimg.com/originals/c4/cd/26/c4cd26501ebe3b52c613d4395980b297.jpg',
		time: '10:30',
		ava: 'https://kartinki.pics/uploads/posts/2022-02/1644923012_19-kartinkin-net-p-kartinki-dlya-patsanov-21.jpg',
		videoName: 'React Hooks Tutorial',
		user: 'Matthew Miller',
		numberOfViews: '9 тыс',
		releaseTime: 'вчера',
	},
	{
		img: 'https://games.mail.ru/hotbox/content_files/news/2022/07/28/0929e053a00e427ea3554a4945c9e4a4.jpg',
		time: '17:40',
		ava: 'https://starbiography.ru/wp-content/uploads/2021/06/1-1.jpg',
		videoName: 'Node.js Basics',
		user: 'Olivia Davis',
		numberOfViews: '6 тыс',
		releaseTime: '4 часа назад',
	},
	{
		img: 'https://i.playground.ru/p/U1zNk40-QcC7xJXooJHS1Q.jpeg',
		time: '22:15',
		ava: 'https://www.hnldesign.nl/wp-content/uploads/2013/03/TheStig1.jpg',
		videoName: 'Vue.js Introduction',
		user: 'Daniel White',
		numberOfViews: '11 млн',
		releaseTime: '1 неделю назад',
	},
	{
		img: 'https://i.ytimg.com/vi/alwRjts-MtY/maxresdefault.jpg',
		time: '13:05',
		ava: 'https://mykaleidoscope.ru/x/uploads/posts/2022-10/1666196261_6-mykaleidoscope-ru-p-oboi-s-kotikami-vkontakte-6.jpg',
		videoName: 'Java Programming for Beginners',
		user: 'Chloe Johnson',
		numberOfViews: '4 тыс',
		releaseTime: '3 часа назад',
	},
	{
		img: 'https://virtus-img.cdnvideo.ru/images/og-jpg/plain/cf/cf2becb6-dae9-4b69-8caf-bcb6d4ae1f28.jpg',
		time: '20:50',
		ava: 'https://klike.net/uploads/posts/2022-08/1661172239_j-12.jpg',
		videoName: 'Django Web Framework',
		user: 'James Brown',
		numberOfViews: '14 млн',
		releaseTime: '2 дня назад',
	},
	{
		img: '/public/ObloshjkaVideoTest.jpg',
		time: '11:46',
		ava: '/public/testAvaVersion.jpg',
		videoName:
			'Ultimate Tailwind CSS Tutorial // Build a Discord-inspired Animated Navbar',
		user: 'Elena Kovalenko',
		numberOfViews: '10 млн',
		releaseTime: '3 дня назад',
	},
	{
		img: '/public/ObloshjkaVideoTest2.png',
		time: '09:21',
		ava: '/public/testAvaVersion2.jpg',
		videoName:
			'Атомная батарея для «вечных» смартфонов, Торвальдс ругается, Сертификация GitHub стала общедоступной',
		user: 'Sergey Nemchinskiy',
		numberOfViews: '2 тыс',
		releaseTime: '18 минут назад',
	},
	{
		img: '/public/ObloshjkaVideoTest3.jpg',
		time: '06:58',
		ava: '/public/testAvaVersion3.jpg',
		videoName: 'MacBook Air на Windows от Huawei',
		user: 'Wylsacom',
		numberOfViews: '10 млн',
		releaseTime: '4 часа назад',
	},

	{
		img: '/public/ObloshjkaVideoTest4.jpg',
		time: '19:24',
		ava: '/public/testAvaVersion4.jpg',
		videoName:
			'Атомная батарея для «вечных» смартфонов, Торвальдс ругается, Сертификация GitHub стала общедоступной',
		user: 'Mikhail Kuznetsov',
		numberOfViews: '2 тыс',
		releaseTime: 'вчера',
	},
	{
		img: '/public/ObloshjkaVideoTest5.jpg',
		time: '22:36',
		ava: '/public/testAvaVersion5.jpg',
		videoName: 'Это реально моя копия ютуба, шариш, меееен?',
		user: 'Timmi',
		numberOfViews: '100 млн',
		releaseTime: '30 лет назад',
	},
	{
		img: '/public/ObloshjkaVideoTest6.jpg',
		time: '5:21',
		ava: '/public/testAvaVersion6.jpg',
		videoName:
			'Атомная батарея для «вечных» смартфонов, Торвальдс ругается, Сертификация GitHub стала общедоступной',
		user: 'Andrei Smirnov',
		numberOfViews: '2 тыс',
		releaseTime: '3 месяца назад',
	},
	{
		img: '/public/ObloshjkaVideoTest7.jpg',
		time: '09:53',
		ava: '/public/testAvaVersion7.jpg',
		videoName:
			'Ultimate Tailwind CSS Tutorial // Build a Discord-inspired Animated Navbar',
		user: 'Pavel Kozlov',
		numberOfViews: '10 млн',
		releaseTime: '3 дня назад',
	},

	{
		img: '/public/ObloshjkaVideoTest8.jpg',
		time: '18:14',
		ava: '/public/testAvaVersion8.jpg',
		videoName:
			'Атомная батарея для «вечных» смартфонов, Торвальдс ругается, Сертификация GitHub стала общедоступной',
		user: 'Victor Ivanov',
		numberOfViews: '2 тыс',
		releaseTime: '14 лет назад',
	},
	{
		img: '/public/ObloshjkaVideoTest9.jpg',
		time: '16:50',
		ava: '/public/testAvaVersion9.jpg',
		videoName:
			'Ultimate Tailwind CSS Tutorial // Build a Discord-inspired Animated Navbar',
		user: 'Dmitry Kuznetsov',
		numberOfViews: '10 млн',
		releaseTime: '2 минуты назад',
	},
	{
		img: '/public/ObloshjkaVideoTest10.jpg',
		time: '22:40',
		ava: '/public/testAvaVersion10.jpg',
		videoName:
			'Атомная батарея для «вечных» смартфонов, Торвальдс ругается, Сертификация GitHub стала общедоступной',
		user: 'Anna Ivanova',
		numberOfViews: '2 тыс',
		releaseTime: '4 часа назад',
	},
	{
		img: '/public/ObloshjkaVideoTest11.jpg',
		time: '15:29',
		ava: '/public/testAvaVersion11.jpg',
		videoName:
			'Ultimate Tailwind CSS Tutorial // Build a Discord-inspired Animated Navbar',
		user: 'MORGENSHTERN',
		numberOfViews: '10 млн',
		releaseTime: '12 лет назад',
	},

	{
		img: '/public/ObloshjkaVideoTest12.jpg',
		time: '22:40',
		ava: '/public/testAvaVersion12.jpg',
		videoName:
			'Атомная батарея для «вечных» смартфонов, Торвальдс ругается, Сертификация GitHub стала общедоступной',
		user: 'Sergey Nemchinskiy',
		numberOfViews: '2 тыс',
		releaseTime: '15 сек назад',
	},
	{
		img: '/public/ObloshjkaVideoTest.jpg',
		time: '11:46',
		ava: '/public/testAvaVersion.jpg',
		videoName:
			'Ultimate Tailwind CSS Tutorial // Build a Discord-inspired Animated Navbar',
		user: 'Elena Kovalenko',
		numberOfViews: '10 млн',
		releaseTime: '3 дня назад',
	},
	{
		img: '/public/ObloshjkaVideoTest2.png',
		time: '09:21',
		ava: '/public/testAvaVersion2.jpg',
		videoName:
			'Атомная батарея для «вечных» смартфонов, Торвальдс ругается, Сертификация GitHub стала общедоступной',
		user: 'Sergey Nemchinskiy',
		numberOfViews: '2 тыс',
		releaseTime: '18 минут назад',
	},
	{
		img: '/public/ObloshjkaVideoTest3.jpg',
		time: '06:58',
		ava: '/public/testAvaVersion3.jpg',
		videoName: 'MacBook Air на Windows от Huawei',
		user: 'Wylsacom',
		numberOfViews: '10 млн',
		releaseTime: '4 часа назад',
	},

	{
		img: '/public/ObloshjkaVideoTest4.jpg',
		time: '19:24',
		ava: '/public/testAvaVersion4.jpg',
		videoName:
			'Атомная батарея для «вечных» смартфонов, Торвальдс ругается, Сертификация GitHub стала общедоступной',
		user: 'Mikhail Kuznetsov',
		numberOfViews: '2 тыс',
		releaseTime: 'вчера',
	},
	{
		img: '/public/ObloshjkaVideoTest5.jpg',
		time: '22:36',
		ava: '/public/testAvaVersion5.jpg',
		videoName: 'Это реально моя копия ютуба, шариш, меееен?',
		user: 'Timmi',
		numberOfViews: '100 млн',
		releaseTime: '30 лет назад',
	},
	{
		img: '/public/ObloshjkaVideoTest6.jpg',
		time: '5:21',
		ava: '/public/testAvaVersion6.jpg',
		videoName:
			'Атомная батарея для «вечных» смартфонов, Торвальдс ругается, Сертификация GitHub стала общедоступной',
		user: 'Andrei Smirnov',
		numberOfViews: '2 тыс',
		releaseTime: '3 месяца назад',
	},
	{
		img: '/public/ObloshjkaVideoTest7.jpg',
		time: '09:53',
		ava: '/public/testAvaVersion7.jpg',
		videoName:
			'Ultimate Tailwind CSS Tutorial // Build a Discord-inspired Animated Navbar',
		user: 'Pavel Kozlov',
		numberOfViews: '10 млн',
		releaseTime: '3 дня назад',
	},

	{
		img: '/public/ObloshjkaVideoTest8.jpg',
		time: '18:14',
		ava: '/public/testAvaVersion8.jpg',
		videoName:
			'Атомная батарея для «вечных» смартфонов, Торвальдс ругается, Сертификация GitHub стала общедоступной',
		user: 'Victor Ivanov',
		numberOfViews: '2 тыс',
		releaseTime: '14 лет назад',
	},
	{
		img: '/public/ObloshjkaVideoTest9.jpg',
		time: '16:50',
		ava: '/public/testAvaVersion9.jpg',
		videoName:
			'Ultimate Tailwind CSS Tutorial // Build a Discord-inspired Animated Navbar',
		user: 'Dmitry Kuznetsov',
		numberOfViews: '10 млн',
		releaseTime: '2 минуты назад',
	},
	{
		img: '/public/ObloshjkaVideoTest10.jpg',
		time: '22:40',
		ava: '/public/testAvaVersion10.jpg',
		videoName:
			'Атомная батарея для «вечных» смартфонов, Торвальдс ругается, Сертификация GitHub стала общедоступной',
		user: 'Anna Ivanova',
		numberOfViews: '2 тыс',
		releaseTime: '4 часа назад',
	},
	{
		img: '/public/ObloshjkaVideoTest11.jpg',
		time: '15:29',
		ava: '/public/testAvaVersion11.jpg',
		videoName:
			'Ultimate Tailwind CSS Tutorial // Build a Discord-inspired Animated Navbar',
		user: 'MORGENSHTERN',
		numberOfViews: '10 млн',
		releaseTime: '12 лет назад',
	},

	{
		img: '/public/ObloshjkaVideoTest12.jpg',
		time: '22:40',
		ava: '/public/testAvaVersion12.jpg',
		videoName:
			'Атомная батарея для «вечных» смартфонов, Торвальдс ругается, Сертификация GitHub стала общедоступной',
		user: 'Sergey Nemchinskiy',
		numberOfViews: '2 тыс',
		releaseTime: '15 сек назад',
	},
	{
		img: 'https://games.mail.ru/hotbox/content_files/news/2022/07/28/0929e053a00e427ea3554a4945c9e4a4.jpg',
		time: '08:15',
		ava: 'https://www.zastavki.com/pictures/2560x1600/2011/People_Different_people_The_military_man_028158_.jpg',
		videoName: 'How to Build a React App from Scratch',
		user: 'John Doe',
		numberOfViews: '5 тыс',
		releaseTime: '2 дня назад',
	},
	{
		img: 'https://zone64.ru/wp-content/uploads/2023/03/sa.jpeg',
		time: '12:45',
		ava: 'https://yt3.googleusercontent.com/l3RA78xrTJ1CmEzZjRAImN08nO5QKqK8xTtk_9TNj-P1p0TE38CFwpzBhcEByo1wWzh9q5RbZSw=s900-c-k-c0x00ffffff-no-rj',
		videoName: 'Introduction to Machine Learning',
		user: 'Alice Johnson',
		numberOfViews: '8 млн',
		releaseTime: '5 часов назад',
	},
	{
		img: 'https://avatars.dzeninfra.ru/get-zen_doc/2377661/pub_5eb7bd62046ed81479ddb434_5eb7c310d2c91417688d2dc0/scale_1200',
		time: '15:30',
		ava: 'https://funpick.ru/wp-content/uploads/2018/03/krut-kar-dlya-pats-6.jpg',
		videoName: 'Web Development Best Practices',
		user: 'Bob Smith',
		numberOfViews: '3 тыс',
		releaseTime: 'вчера',
	},
	{
		img: 'https://mail.9net.ru/uploads/posts/2019-08/1566477942_tenderli.jpg',
		time: '21:10',
		ava: 'https://wallbox.ru/wallpapers/main2/201732/1502385344598c94c1011c04.86328460.jpg',
		videoName: 'JavaScript Tips and Tricks',
		user: 'Emma Brown',
		numberOfViews: '12 млн',
		releaseTime: '1 неделю назад',
	},
	{
		img: 'https://schtirlitz.ru/800/600/https/moreklientov.com/wp-content/uploads/2018/02/%D0%9F%D1%80%D0%BE%D0%B4%D0%B2%D0%B8%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BD%D0%B0-%D0%AE%D1%82%D1%83%D0%B1-9.png',
		time: '09:25',
		ava: 'https://zabavdom.ru/wp-content/uploads/2/a/7/2a79a3c979af26cb7a4f1a89cec18629.jpeg',
		videoName: 'CSS Flexbox Tutorial',
		user: 'Amelia Taylor',
		numberOfViews: '10 тыс',
		releaseTime: 'вчера',
	},
	{
		img: 'https://vsrap.ru/wp-content/uploads/2019/12/pewdiepie.jpg',
		time: '16:20',
		ava: 'https://i.yapx.cc/RFzQV.jpg',
		videoName: 'Python Flask Tutorial',
		user: 'Logan Davis',
		numberOfViews: '8 тыс',
		releaseTime: '5 часов назад',
	},
	{
		img: 'https://i.playground.ru/p/YwIb9drQ6g-SJhgH3w2Jig.jpeg',
		time: '21:30',
		ava: 'https://klike.net/uploads/posts/2022-08/1661867842_j-96.jpg',
		videoName: 'JavaScript ES6 Features',
		user: 'Ella Wilson',
		numberOfViews: '12 млн',
		releaseTime: '1 неделю назад',
	},
	{
		img: 'https://static.life.ru/publications/2020/9/20/790206591784.3093.JPG',
		time: '11:10',
		ava: 'https://proprikol.ru/wp-content/uploads/2020/06/kartinki-dlya-stima-na-avu-10.jpg',
		videoName: 'React Native Tutorial',
		user: 'Jackson Miller',
		numberOfViews: '7 тыс',
		releaseTime: '3 часа назад',
	},
	{
		img: 'https://i.ytimg.com/vi/BgYP6z4HeBA/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgWyhXMA8=&rs=AOn4CLAd_zSu4TpZ0v2J2mJgBK78bD81hA',
		time: '18:45',
		ava: 'https://img.razrisyika.ru/kart/86/1200/341354-klevye-8.jpg',
		videoName: 'Node.js REST API',
		user: 'Scarlett Davis',
		numberOfViews: '6 тыс',
		releaseTime: '4 часа назад',
	},
	{
		img: 'https://games.mail.ru/hotbox/content_files/news/2022/07/28/0929e053a00e427ea3554a4945c9e4a4.jpg',
		time: '23:20',
		ava: 'https://i.ytimg.com/vi/_fTA6lY7sKs/maxresdefault.jpg',
		videoName: 'Vue.js Components',
		user: 'Mason White',
		numberOfViews: '11 млн',
		releaseTime: '1 неделю назад',
	},
	{
		img: 'https://sneg.top/uploads/posts/2023-06/1687762327_sneg-top-p-avatarki-strimerov-krasivo-2.jpg',
		time: '14:05',
		ava: 'https://game-roblox.ru/wp-content/uploads/2020/07/unnamed-4-2.jpg',
		videoName: 'Java OOP Concepts',
		user: 'Ava Johnson',
		numberOfViews: '4 тыс',
		releaseTime: '3 часа назад',
	},
	{
		img: 'https://gameguru.ru/clf/3a/bb/6b/6b/articles.sodapoppin.jpg',
		time: '20:30',
		ava: 'https://i.pinimg.com/736x/45/98/6b/45986b577af3b3de663a07505eb5c176.jpg',
		videoName: 'Django Models Tutorial',
		user: 'Henry Brown',
		numberOfViews: '14 млн',
		releaseTime: '2 дня назад',
	},
	{
		img: 'https://vsrap.ru/wp-content/uploads/2020/08/bez-imeni-1-19.jpg',
		time: '09:15',
		ava: 'https://images.hdqwalls.com/download/anonymus-guy-4k-az-2932x2932.jpg',
		videoName: 'CSS Animation Techniques',
		user: 'Lily Wilson',
		numberOfViews: '10 тыс',
		releaseTime: 'вчера',
	},
	{
		img: 'https://cdni-vm.servicecdn.ru/2020.10/original/1200_5f8d478782682c554507a227.png',
		time: '16:40',
		ava: 'https://hdoboi.kiev.ua/images/05.Jun.2019-paren-v-protivogaze-4k.jpg',
		videoName: 'Python Django Tutorial',
		user: 'Owen Taylor',
		numberOfViews: '8 тыс',
		releaseTime: '5 часов назад',
	},
	{
		img: 'https://celes.club/uploads/posts/2022-05/thumbs/1652434608_45-celes-club-p-strimer-art-krasivo-50.jpg',
		time: '22:05',
		ava: 'https://i.pinimg.com/originals/70/b7/a5/70b7a53129d91567390eee82fb4e7bf9.jpg',
		videoName: 'JavaScript Promises',
		user: 'Eva Davis',
		numberOfViews: '12 млн',
		releaseTime: '1 неделю назад',
	},
	{
		img: 'https://i.ytimg.com/vi/-2dzp3HALPs/maxresdefault.jpg',
		time: '11:40',
		ava: 'https://klike.net/uploads/posts/2023-02/1675926305_3-23.jpg',
		videoName: 'React Context API',
		user: 'Gabriel Wilson',
		numberOfViews: '7 тыс',
		releaseTime: '3 часа назад',
	},
	{
		img: 'https://i.ytimg.com/vi/QTkOAM6mmNs/maxresdefault.jpg',
		time: '19:15',
		ava: 'https://w-dog.ru/wallpapers/1/31/464217882479635/tvorchestvo-solncezashhitnye-ochki-kot.jpg',
		videoName: 'Node.js Express Tutorial',
		user: 'Aria Miller',
		numberOfViews: '6 тыс',
		releaseTime: '4 часа назад',
	},
	{
		img: 'https://kartinki.pics/uploads/posts/2022-03/1648021005_12-kartinkin-net-p-kartinki-na-strim-18.jpg',
		time: '23:50',
		ava: 'https://klike.net/uploads/posts/2022-08/1661867880_j-76.jpg',
		videoName: 'Vue.js Directives',
		user: 'Mia White',
		numberOfViews: '11 млн',
		releaseTime: '1 неделю назад',
	},

	{
		img: '/public/ObloshjkaVideoTest4.jpg',
		time: '01:12:54',
		ava: 'https://klike.net/uploads/posts/2022-08/1661867880_j-76.jpg',
		videoName: 'Ахуеть, хауди хуй',
		user: 'Timmi',
		numberOfViews: '249 млн',
		releaseTime: '2 часа назад',
	},
]

export { videoItem }
