export const SHOW_HIDE_CREATE_VIDEO_MODAL = 'SHOW_HIDE_CREATE_VIDEO_MODAL'
export const SHOW_HIDE_ALLOWS_MODAL = 'SHOW_HIDE_ALLOWS_MODAL'
export const SHOW_HIDE_PROFILE_MODAL = 'SHOW_HIDE_PROFILE_MODAL'
